"use strict";
const fs = require("fs");
const path = require("path");
const os = require("os");

const ORDER = ["typemap.js", "engine.js", "selection.js", "panel.js", "selftest.js", "entry.js"];
const srcDir = path.join(__dirname, "src");
const distDir = path.join(__dirname, "dist");

function build() {
  fs.mkdirSync(distDir, { recursive: true });
  let out = "// GENERATED by build.js — do not edit. Edit src/*.js instead.\n\n";
  for (const f of ORDER) {
    const p = path.join(srcDir, f);
    if (!fs.existsSync(p)) continue;
    out += "// ===== " + f + " =====\n" + fs.readFileSync(p, "utf8") + "\n\n";
  }
  const target = path.join(distDir, "MoGraph.js");
  fs.writeFileSync(target, out, "utf8");
  console.log("Built " + target + " (" + out.length + " bytes)");

  if (process.argv.includes("--install")) {
    const dest = path.join(os.homedir(), "AppData", "Roaming", "Cavalry", "Scripts", "MoGraph.js");
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(target, dest);
    console.log("Installed to " + dest);
  }
}
build();
